name: applied-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - asttokens=2.4.1
  - bzip2
  - ca-certificates
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat
  - importlib-metadata=8.5.0
  - ipykernel
  - ipython
  - jedi=0.19.1
  - jupyter_client
  - jupyter_core
  - krb5
  - libffi
  - libsodium
  - matplotlib-inline
  - nest-asyncio=1.6.0
  - openssl
  - packaging=24.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip
  - platformdirs=4.3.6
  - prompt-toolkit
  - psutil
  - pure_eval
  - pygments
  - pyzmq
  - setuptools
  - six=1.16.0
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib

# Pip dependencies
  - pip:
      - aiosignal==1.3.1
      - alembic==1.13.3
      - attrs==24.2.0
      - autocfg==0.0.8
      - bayesian-optimization==1.5.1
      - certifi
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - future==1.0.0
      - gluoncv==0.10.5.post0
      - greenlet==3.1.1
      - hyperopt==0.2.7
      - idna==3.10
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - mako==1.3.5
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.2.1
      - numpy==2.1.1
      - opencv-python==4.10.0.84
      - optuna==4.0.0
      - pandas==2.2.3
      - pillow==10.4.0
      - portalocker==2.10.1
      - protobuf==5.28.2
      - py-cpuinfo==9.0.0
      - py4j==0.10.9.7
      - pyarrow==17.0.0
      - pycocotools==2.0.8
      - pyparsing==3.1.4
      - pytz==2024.2
      - pyyaml==6.0.2
      - ray==2.37.0
      - referencing==0.35.1
      - requests==2.32.3
      - rpds-py==0.20.0
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - sqlalchemy==2.0.35
      - sympy==1.12
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tqdm==4.66.5
      - tzdata==2024.2
      - ultralytics==8.3.9
      - ultralytics-thop==2.0.9
      - urllib3==2.2.3
      - xgboost==2.1.1
      - yacs==0.1.8
